<Project Sdk="Microsoft.NET.Sdk">

  <PropertyGroup>
    <OutputType>Exe</OutputType>
  </PropertyGroup>

  <ItemGroup>
    <PackageReference Include="Bogus" Version="35.6.1" />
  </ItemGroup>

  <ItemGroup>
    <ProjectReference Include="../EntityResolution.Core/EntityResolution.Core.csproj" />
  </ItemGroup>

</Project>
